allowBuilds:
  "@parcel/watcher": true
  better-sqlite3: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@azisaba/graph@0.1.0-rc.2 || 0.1.0-rc.3 || 0.1.0-rc.5 || 0.1.0-rc.6 || 0.1.0-rc.7'
onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - sharp
